<?php
session_regenerate_id();
$_SESSION['WAY'] = "CLAIM";  //"CLAIM"-pretenzija, "EVENT"-notikums,"TASK"- uzdevums
$_SESSION['STATUS'] = "LIST"; // 'VIEW','EDIT','LIST'
$_SESSION['TITLE'] = "Pretenziju saraksts";
$_SESSION['DEBUG'] ='';
$_SESSION['FORMA'] = 'pret_list.php';
$_SESSION['FORM_TITLE'] = -1;
$_SESSION['NAVIG'] = -1;
$_SESSION['VERSIJA'] = '';
$_SESSION['MAIL'] = 'N';

$_SESSION['AGENTS']['VARDS'] = '';
$_SESSION['AGENTS']['PASTS'] = '';
$_SESSION['AGENTS']['ID'] = 0;
$_SESSION['AGENTS']['STRUKT'] = 0;

$_SESSION['USER']['ID'] = 0;
$_SESSION['USER']['VARDS'] = '';
$_SESSION['USER']['TIESIBAS'] = '';
$_SESSION['USER']['LOMA'] = '';
$_SESSION['USER']['STRUKT'] = '';
$_SESSION['USER']['STATUS']=0;

$_SESSION['QUALITY']['ID'] = 0;
$_SESSION['QUALITY']['VARDS'] = '';
$_SESSION['QUALITY']['TIESIBAS'] = '';
$_SESSION['QUALITY']['LOMA'] = '';
$_SESSION['QUALITY']['EPASTS']='';

$_SESSION['PRET']['REG_NR'] = "";
$_SESSION['PRET']['PREFIKS'] = "KM";
$_SESSION['PRET']['PASUT_NR'] = "";
$_SESSION['PRET']['KLIENTS'] = "";
$_SESSION['PRET']['KODS'] = "";
$_SESSION['PRET']['STATUS']=""; // "LOADED","REGISTERED","PROCESS","DECISION" - lēmums,"ACCEPTED","CORRECTIVE"
$_SESSION['PRET']['ID']=0;
$_SESSION['PRET']['SAKUMS']="0000-00-00";
$_SESSION['PRET']['BEIGAS']="0000-00-00";
$_SESSION['PRET']['NOTIKUMU_SK']=0;
$_SESSION['PRET']['IZDEVUMI']="";

$_SESSION['TASK']['ID']="";
$_SESSION['TASK']['KODS']="";
$_SESSION['TASK']['NR']=0;
$_SESSION['TASK']['PERS_ID']="";
$_SESSION['TASK']['PERS_VARDS']="";
$_SESSION['TASK']['PERS_PASTS']="";
$_SESSION['TASK']['STATUS']="";

$_SESSION['EVENTS']['STATUS'] ="";
$_SESSION['EVENTS']['ID'] =0;
$_SESSION['EVENTS']['NR'] =0;
$_SESSION['EVENTS']['KODS'] ='';
$_SESSION['EVENTS']['PERS_SK'] =0;
$_SESSION['EVENTS']['FAIL_SK'] =0;
$_SESSION['EVENTS']['VEIDS'] =''; //UZDEVUMS, ZINOJUMS, LEMUMS, NOSLEGUMS, PREVENT
$_SESSION['EVENTS']['VEIDS_NOS'] ='';
$_SESSION['EVENTS']['AGENTS'] ='';
$_SESSION['EVENTS']['NEWFORMA'] ='';
$_SESSION['EVENTS']['FORMA'] ='';


session_write_close();
